# Generated by Django 4.2.3 on 2023-08-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.TextField(max_length=500)),
                ('phone_no', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('head_branch', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Address',
            },
        ),
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='upload')),
                ('appointment_text', models.TextField(max_length=500)),
                ('appointment_number', models.CharField(max_length=200)),
                ('copyright_text', models.TextField(max_length=500)),
                ('facebook', models.URLField()),
                ('twitter', models.URLField()),
                ('instagram', models.URLField()),
                ('linkedin', models.URLField()),
                ('address', models.ManyToManyField(to='global_settings.address')),
            ],
            options={
                'verbose_name': 'Global Setting',
            },
        ),
    ]
