# Generated by Django 4.2.3 on 2023-09-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('link', models.URLField()),
                ('icon_class', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='twitter',
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='social',
            field=models.ManyToManyField(to='global_settings.social'),
        ),
    ]
