# Generated by Django 4.2.3 on 2023-09-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_settings', '0002_social_remove_globalsettings_facebook_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globalsettings',
            old_name='appointment_number',
            new_name='company_number',
        ),
        migrations.RenameField(
            model_name='globalsettings',
            old_name='appointment_text',
            new_name='welcome_text',
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='ceo_sign',
            field=models.ImageField(blank=True, null=True, upload_to='upload'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='logo_dark',
            field=models.ImageField(blank=True, null=True, upload_to='upload'),
        ),
    ]
