# Generated by Django 4.2.3 on 2023-08-07 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='upload')),
            ],
            options={
                'verbose_name': 'Images',
            },
        ),
        migrations.CreateModel(
            name='SliderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_text', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(max_length=500)),
                ('button_text', models.CharField(max_length=200)),
                ('button_link', models.URLField()),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.image')),
            ],
            options={
                'verbose_name': 'Slider Items',
            },
        ),
    ]
