# Generated by Django 4.2.3 on 2023-08-07 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_welcomesection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='welcomesection',
            options={'verbose_name': 'Welcome Section'},
        ),
        migrations.RemoveField(
            model_name='welcomesection',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='welcomesection',
            name='image',
        ),
        migrations.CreateModel(
            name='PracticeAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(max_length=500)),
                ('icon', models.CharField(max_length=200)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.image')),
            ],
            options={
                'verbose_name': 'Practice Area',
            },
        ),
    ]
