# Generated by Django 4.2.3 on 2023-08-26 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_experiences_faq_team_testimonial_whatwediditem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.image'),
        ),
    ]
