# Generated by Django 4.2.3 on 2023-08-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_team_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'Faq'},
        ),
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Advanced Topics', 'Advanced Topics')], default='General', max_length=20),
        ),
    ]
