# Generated by Django 4.2.3 on 2023-08-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_alter_faq_options_faq_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practiceareas',
            options={'verbose_name': 'Service'},
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Advanced', 'Advanced')], default='General', max_length=20),
        ),
    ]
