# Generated by Django 4.2.3 on 2023-09-03 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_alter_practiceareas_options_alter_faq_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slideritem',
            options={'verbose_name': 'Hero Items'},
        ),
        migrations.RenameField(
            model_name='slideritem',
            old_name='before_text',
            new_name='welcome_text',
        ),
        migrations.AddField(
            model_name='slideritem',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
