# Generated by Django 4.2.3 on 2023-09-03 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_alter_slideritem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whatwedid',
            options={'verbose_name': 'Work Counter'},
        ),
        migrations.AlterModelOptions(
            name='whatwediditem',
            options={'verbose_name': 'Work Counter Item'},
        ),
        migrations.RemoveField(
            model_name='whatwedid',
            name='description',
        ),
        migrations.RemoveField(
            model_name='whatwediditem',
            name='description',
        ),
        migrations.AddField(
            model_name='whatwediditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload'),
        ),
        migrations.AlterField(
            model_name='whatwedid',
            name='item',
            field=models.ManyToManyField(blank=True, null=True, to='manager.whatwediditem'),
        ),
    ]
