# Generated by Django 4.2.3 on 2023-09-03 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_alter_whatwedid_options_alter_whatwediditem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='welcomesection',
            options={'verbose_name': 'Who we are'},
        ),
        migrations.RenameField(
            model_name='welcomesection',
            old_name='text',
            new_name='desscription',
        ),
        migrations.AddField(
            model_name='welcomesection',
            name='image_horizontal',
            field=models.ImageField(blank=True, null=True, upload_to='upload'),
        ),
        migrations.AddField(
            model_name='welcomesection',
            name='image_vertical',
            field=models.ImageField(blank=True, null=True, upload_to='upload'),
        ),
    ]
