# Generated by Django 4.2.3 on 2023-09-03 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_alter_welcomesection_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='upload')),
            ],
            options={
                'verbose_name': 'Work Technology',
            },
        ),
        migrations.CreateModel(
            name='WorkTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Mobile Application', 'Mobile Application'), ('Database', 'Database')], default='Frontend', max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='upload')),
            ],
            options={
                'verbose_name': 'Work Technology',
            },
        ),
    ]
