# Generated by Django 4.2.3 on 2023-09-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_industry_worktechnology'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='upload')),
            ],
            options={
                'verbose_name': 'Client Company',
            },
        ),
        migrations.AlterModelOptions(
            name='industry',
            options={'verbose_name': 'Serve Industry'},
        ),
    ]
