# Generated by Django 4.2.3 on 2023-09-03 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_clientlogo_alter_industry_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatwedid',
            name='item',
            field=models.ManyToManyField(to='manager.whatwediditem'),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('images', models.ManyToManyField(to='manager.image')),
            ],
            options={
                'verbose_name': 'Gallery',
            },
        ),
    ]
