# Generated by Django 4.2.3 on 2023-09-03 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_settings', '0002_social_remove_globalsettings_facebook_and_more'),
        ('manager', '0013_alter_whatwedid_item_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='team',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='team',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='team',
            name='twitter',
        ),
        migrations.AddField(
            model_name='team',
            name='social',
            field=models.ManyToManyField(to='global_settings.social'),
        ),
    ]
