# Generated by Django 4.2.3 on 2023-09-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_rename_job_title_team_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcomesection',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
