# Generated by Django 4.2.3 on 2023-09-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_whatwediditem_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload'),
        ),
    ]
